dependencies:
- name: template-node-react
  version: 0.1.0
  repository: http://artifactory.showcase-dev-rhos-cluster.us-south.containers.appdomain.cloud/artifactory/generic-local/showcase-dev-openshift/index.yaml
