dependencies:
- name: template-node-react
  version: 5.0.2
  repository: http://artifactory.showcase-dev-rhos-cluster.us-south.containers.appdomain.cloud/artifactory/generic-local/showcase-dev-openshift
