apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: myapp-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: myapp-ui
  template:
    metadata:
      labels:
        app: myapp-ui
    spec:
      imagePullSecrets:
        - name: test-us-icr-io
      containers:
      - image: us.icr.io/showcase-dev-openshift/ui-app:1.0.0-1
        name: myapp-ui
        ports:
        - containerPort: 3000
