apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ui-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ui-app
  template:
    metadata:
      labels:
        app: ui-app
    spec:
      imagePullSecrets:
        - name: dev-us-icr-io
      containers:
        - image: us.icr.io/showcase-dev-openshift/ui-app:1.0.0-1
          name: ui-app
          ports:
            containerPort: 3000
