apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ui-app
  namespace: test
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ui-app
  template:
    metadata:
      labels:
        app: ui-app
    spec:
      imagePullSecrets:
        - name: default-us-icr-io
      containers:
        - name: ui-app
          image: us.icr.io/showcase-dev-openshift/ui-app:1.0.0-1
          imagePullPolicy: IfNotPresent
      ports:
        - name: http
          containerPort: 3000
          protocol: TCP
